### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Luso1221** [xuchenhao001/EASC#1]
Issue 1:
In the Readme file it says we need to start the network using the network.sh file in the folder fabric-samples, but in the main branch there is no such folder.

Issue 2:
If I go back to earlier branches it does exist. I then tried following all the steps properly, but I got this error when I run the curl command to localhost:8888/messages.

<pre><font color="#EF2929">[2023-02-02T12:02:25.888] [ERROR] COMMON - </font>{&quot;status&quot;:&quot;INTERNAL_SERVER_ERROR&quot;,&quot;error&quot;:&quot;Failed to submit transaction: Error: ENOENT: no such file or directory, scandir &apos;/home/osboxes/EASC-clone/EASC/blockchain-server/routes/rest/wallet&apos;&quot;}
</pre>
I tried making a wallet folder inside the blockchain-server/rest/routes/ directory but another error occured:
<pre><font color="#EF2929">[2023-02-02T12:10:48.124] [ERROR] COMMON - </font>{&quot;status&quot;:&quot;INTERNAL_SERVER_ERROR&quot;,&quot;error&quot;:&quot;Failed to submit transaction: TypeError: Cannot read properties of undefined (reading &apos;replace&apos;)&quot;}
</pre>

**Comment by xuchenhao001** [comment]
Thanks for your feedback. 
This project is currently undergoing, so the doc is not up-to-date.
I've updated the README document. There is no need for the blockchain & rest server anymore. 

If you prefer to conduct research on the blockchain, please refer to the AFL project at [AFL](https://github.com/xuchenhao001/AFL). Different from this, it is a finished project.
